package com.ges.plancomptableservice.enums;

public enum NatureCompte {
    CLIENT, FOURNISSEUR,SALARIE,BANQUE,CAISSE,AMORTISE_PROVISE,
    RESULTAT_BILAN,CHARGE,PRODUIT,RESULTAT_GESTION,IMMOBILISATION,
    CAPITAUX,STOCK,TITRE
}
